using System.Text.Json;
using NeversoftMultitool.Core.Formats.GsDump.Oracle;

namespace NeversoftMultitool.Tests.Helpers;

/// <summary>
///     Loads the committed GS-oracle goldens
///     (<c>GoldenFiles/GsOracle/{tag}.gsoracle.json</c> /
///     <c>{tag}.texoracle.json</c>, regenerated by
///     <c>tools/diagnostics/build_gsoracle.ps1</c>) for the adjudication tests.
///     Follows the <see cref="TestPaths" /> convention of resolving the
///     source-tree GoldenFiles directory rather than an output copy.
/// </summary>
internal static class GsOracleGoldenData
{
    private static readonly Lazy<string?> Directory = new(() =>
    {
        var goldenRoot = new TestPaths().GoldenFilesDir;
        if (goldenRoot == null)
            return null;
        var dir = Path.Combine(goldenRoot, "GsOracle");
        return System.IO.Directory.Exists(dir) ? dir : null;
    });

    public static bool HasGoldens =>
        Directory.Value != null &&
        System.IO.Directory.EnumerateFiles(Directory.Value, "*.gsoracle.json").Any();

    public static IEnumerable<(string Tag, GsOracleReport Report)> LoadOracleReports()
    {
        foreach (var path in System.IO.Directory
                     .EnumerateFiles(Directory.Value!, "*.gsoracle.json")
                     .OrderBy(static p => p, StringComparer.Ordinal))
        {
            var report = JsonSerializer.Deserialize(
                File.ReadAllText(path), GsOracleJsonContext.Default.GsOracleReport);
            if (report != null)
                yield return (Path.GetFileName(path).Split('.')[0], report);
        }
    }

    public static IEnumerable<(string Tag, GsTextureOracleReport Report)> LoadTextureOracleReports()
    {
        foreach (var path in System.IO.Directory
                     .EnumerateFiles(Directory.Value!, "*.texoracle.json")
                     .OrderBy(static p => p, StringComparer.Ordinal))
        {
            var report = JsonSerializer.Deserialize(
                File.ReadAllText(path), GsOracleJsonContext.Default.GsTextureOracleReport);
            if (report != null)
                yield return (Path.GetFileName(path).Split('.')[0], report);
        }
    }
}
