namespace NeversoftMultitool.Core.Formats.Qb;

/// <summary>
///     QB token types from THUG source: Gel/Scripting/tokens.h
///     Values are single bytes (0-68). Token sizes from skiptoken.cpp.
/// </summary>
public enum QbTokenType : byte
{
    EndOfFile = 0,
    EndOfLine = 1,
    EndOfLineNumber = 2,
    StartStruct = 3,
    EndStruct = 4,
    StartArray = 5,
    EndArray = 6,
    Equals = 7,
    Dot = 8,
    Comma = 9,
    Minus = 10,
    Add = 11,
    Divide = 12,
    Multiply = 13,
    OpenParenth = 14,
    CloseParenth = 15,
    DebugInfo = 16,
    SameAs = 17,
    LessThan = 18,
    LessThanEqual = 19,
    GreaterThan = 20,
    GreaterThanEqual = 21,
    Name = 22,
    Integer = 23,
    HexInteger = 24,
    Enum = 25,
    Float = 26,
    String = 27,
    LocalString = 28,
    Array = 29,
    Vector = 30,
    Pair = 31,
    KeywordBegin = 32,
    KeywordRepeat = 33,
    KeywordBreak = 34,
    KeywordScript = 35,
    KeywordEndScript = 36,
    KeywordIf = 37,
    KeywordElse = 38,
    KeywordElseIf = 39,
    KeywordEndIf = 40,
    KeywordReturn = 41,
    Undefined = 42,
    ChecksumName = 43,
    KeywordAllArgs = 44,
    Arg = 45,
    Jump = 46,
    KeywordRandom = 47,
    KeywordRandomRange = 48,
    At = 49,
    Or = 50,
    And = 51,
    Xor = 52,
    ShiftLeft = 53,
    ShiftRight = 54,
    KeywordRandom2 = 55,
    KeywordRandomRange2 = 56,
    KeywordNot = 57,
    KeywordAnd = 58,
    KeywordOr = 59,
    KeywordSwitch = 60,
    KeywordEndSwitch = 61,
    KeywordCase = 62,
    KeywordDefault = 63,
    KeywordRandomNoRepeat = 64,
    KeywordRandomPermute = 65,
    Colon = 66,
    RuntimeCFunction = 67,
    RuntimeMemberFunction = 68,
}

public static class QbTokenInfo
{
    public static string GetTokenName(QbTokenType type) => type switch
    {
        QbTokenType.EndOfFile => "ENDOFFILE",
        QbTokenType.EndOfLine => "ENDOFLINE",
        QbTokenType.EndOfLineNumber => "ENDOFLINENUMBER",
        QbTokenType.StartStruct => "STARTSTRUCT",
        QbTokenType.EndStruct => "ENDSTRUCT",
        QbTokenType.StartArray => "STARTARRAY",
        QbTokenType.EndArray => "ENDARRAY",
        QbTokenType.Equals => "EQUALS",
        QbTokenType.Dot => "DOT",
        QbTokenType.Comma => "COMMA",
        QbTokenType.Minus => "MINUS",
        QbTokenType.Add => "ADD",
        QbTokenType.Divide => "DIVIDE",
        QbTokenType.Multiply => "MULTIPLY",
        QbTokenType.OpenParenth => "OPENPARENTH",
        QbTokenType.CloseParenth => "CLOSEPARENTH",
        QbTokenType.DebugInfo => "DEBUGINFO",
        QbTokenType.SameAs => "SAMEAS",
        QbTokenType.LessThan => "LESSTHAN",
        QbTokenType.LessThanEqual => "LESSTHANEQUAL",
        QbTokenType.GreaterThan => "GREATERTHAN",
        QbTokenType.GreaterThanEqual => "GREATERTHANEQUAL",
        QbTokenType.Name => "NAME",
        QbTokenType.Integer => "INTEGER",
        QbTokenType.HexInteger => "HEXINTEGER",
        QbTokenType.Enum => "ENUM",
        QbTokenType.Float => "FLOAT",
        QbTokenType.String => "STRING",
        QbTokenType.LocalString => "LOCALSTRING",
        QbTokenType.Array => "ARRAY",
        QbTokenType.Vector => "VECTOR",
        QbTokenType.Pair => "PAIR",
        QbTokenType.KeywordBegin => "BEGIN",
        QbTokenType.KeywordRepeat => "REPEAT",
        QbTokenType.KeywordBreak => "BREAK",
        QbTokenType.KeywordScript => "SCRIPT",
        QbTokenType.KeywordEndScript => "ENDSCRIPT",
        QbTokenType.KeywordIf => "IF",
        QbTokenType.KeywordElse => "ELSE",
        QbTokenType.KeywordElseIf => "ELSEIF",
        QbTokenType.KeywordEndIf => "ENDIF",
        QbTokenType.KeywordReturn => "RETURN",
        QbTokenType.Undefined => "UNDEFINED",
        QbTokenType.ChecksumName => "CHECKSUM_NAME",
        QbTokenType.KeywordAllArgs => "ALLARGS",
        QbTokenType.Arg => "ARG",
        QbTokenType.Jump => "JUMP",
        QbTokenType.KeywordRandom => "RANDOM",
        QbTokenType.KeywordRandomRange => "RANDOM_RANGE",
        QbTokenType.At => "AT",
        QbTokenType.Or => "OR",
        QbTokenType.And => "AND",
        QbTokenType.Xor => "XOR",
        QbTokenType.ShiftLeft => "SHIFT_LEFT",
        QbTokenType.ShiftRight => "SHIFT_RIGHT",
        QbTokenType.KeywordRandom2 => "RANDOM2",
        QbTokenType.KeywordRandomRange2 => "RANDOM_RANGE2",
        QbTokenType.KeywordNot => "NOT",
        QbTokenType.KeywordAnd => "KEYWORD_AND",
        QbTokenType.KeywordOr => "KEYWORD_OR",
        QbTokenType.KeywordSwitch => "SWITCH",
        QbTokenType.KeywordEndSwitch => "ENDSWITCH",
        QbTokenType.KeywordCase => "CASE",
        QbTokenType.KeywordDefault => "DEFAULT",
        QbTokenType.KeywordRandomNoRepeat => "RANDOM_NO_REPEAT",
        QbTokenType.KeywordRandomPermute => "RANDOM_PERMUTE",
        QbTokenType.Colon => "COLON",
        QbTokenType.RuntimeCFunction => "RUNTIME_CFUNCTION",
        QbTokenType.RuntimeMemberFunction => "RUNTIME_MEMBERFUNCTION",
        _ => $"UNKNOWN({(byte)type})"
    };
}
