namespace NeversoftMultitool.Core.Formats.Qb;

public static class QbTokenInfo
{
    public static string GetTokenName(QbTokenType type)
    {
        return type switch
        {
            QbTokenType.EndOfFile => "ENDOFFILE",
            QbTokenType.EndOfLine => "ENDOFLINE",
            QbTokenType.EndOfLineNumber => "ENDOFLINENUMBER",
            QbTokenType.StartStruct => "STARTSTRUCT",
            QbTokenType.EndStruct => "ENDSTRUCT",
            QbTokenType.StartArray => "STARTARRAY",
            QbTokenType.EndArray => "ENDARRAY",
            QbTokenType.Equals => "EQUALS",
            QbTokenType.Dot => "DOT",
            QbTokenType.Comma => "COMMA",
            QbTokenType.Minus => "MINUS",
            QbTokenType.Add => "ADD",
            QbTokenType.Divide => "DIVIDE",
            QbTokenType.Multiply => "MULTIPLY",
            QbTokenType.OpenParenth => "OPENPARENTH",
            QbTokenType.CloseParenth => "CLOSEPARENTH",
            QbTokenType.DebugInfo => "DEBUGINFO",
            QbTokenType.SameAs => "SAMEAS",
            QbTokenType.LessThan => "LESSTHAN",
            QbTokenType.LessThanEqual => "LESSTHANEQUAL",
            QbTokenType.GreaterThan => "GREATERTHAN",
            QbTokenType.GreaterThanEqual => "GREATERTHANEQUAL",
            QbTokenType.Name => "NAME",
            QbTokenType.Integer => "INTEGER",
            QbTokenType.HexInteger => "HEXINTEGER",
            QbTokenType.Enum => "ENUM",
            QbTokenType.Float => "FLOAT",
            QbTokenType.String => "STRING",
            QbTokenType.LocalString => "LOCALSTRING",
            QbTokenType.Array => "ARRAY",
            QbTokenType.Vector => "VECTOR",
            QbTokenType.Pair => "PAIR",
            QbTokenType.KeywordBegin => "BEGIN",
            QbTokenType.KeywordRepeat => "REPEAT",
            QbTokenType.KeywordBreak => "BREAK",
            QbTokenType.KeywordScript => "SCRIPT",
            QbTokenType.KeywordEndScript => "ENDSCRIPT",
            QbTokenType.KeywordIf => "IF",
            QbTokenType.KeywordElse => "ELSE",
            QbTokenType.KeywordElseIf => "ELSEIF",
            QbTokenType.KeywordEndIf => "ENDIF",
            QbTokenType.KeywordReturn => "RETURN",
            QbTokenType.Undefined => "UNDEFINED",
            QbTokenType.ChecksumName => "CHECKSUM_NAME",
            QbTokenType.KeywordAllArgs => "ALLARGS",
            QbTokenType.Arg => "ARG",
            QbTokenType.Jump => "JUMP",
            QbTokenType.KeywordRandom => "RANDOM",
            QbTokenType.KeywordRandomRange => "RANDOM_RANGE",
            QbTokenType.At => "AT",
            QbTokenType.Or => "OR",
            QbTokenType.And => "AND",
            QbTokenType.Xor => "XOR",
            QbTokenType.ShiftLeft => "SHIFT_LEFT",
            QbTokenType.ShiftRight => "SHIFT_RIGHT",
            QbTokenType.KeywordRandom2 => "RANDOM2",
            QbTokenType.KeywordRandomRange2 => "RANDOM_RANGE2",
            QbTokenType.KeywordNot => "NOT",
            QbTokenType.KeywordAnd => "KEYWORD_AND",
            QbTokenType.KeywordOr => "KEYWORD_OR",
            QbTokenType.KeywordSwitch => "SWITCH",
            QbTokenType.KeywordEndSwitch => "ENDSWITCH",
            QbTokenType.KeywordCase => "CASE",
            QbTokenType.KeywordDefault => "DEFAULT",
            QbTokenType.KeywordRandomNoRepeat => "RANDOM_NO_REPEAT",
            QbTokenType.KeywordRandomPermute => "RANDOM_PERMUTE",
            QbTokenType.Colon => "COLON",
            QbTokenType.RuntimeCFunction => "RUNTIME_CFUNCTION",
            QbTokenType.RuntimeMemberFunction => "RUNTIME_MEMBERFUNCTION",
            _ => $"UNKNOWN({(byte)type})"
        };
    }
}
