namespace NeversoftMultitool.Core.Formats.Qb;

/// <summary>
///     QB token types from THUG source: Gel/Scripting/tokens.h
///     Values are single bytes (0-68). Token sizes from skiptoken.cpp.
/// </summary>
public enum QbTokenType : byte
{
    EndOfFile = 0,
    EndOfLine = 1,
    EndOfLineNumber = 2,
    StartStruct = 3,
    EndStruct = 4,
    StartArray = 5,
    EndArray = 6,
    Equals = 7,
    Dot = 8,
    Comma = 9,
    Minus = 10,
    Add = 11,
    Divide = 12,
    Multiply = 13,
    OpenParenth = 14,
    CloseParenth = 15,
    DebugInfo = 16,
    SameAs = 17,
    LessThan = 18,
    LessThanEqual = 19,
    GreaterThan = 20,
    GreaterThanEqual = 21,
    Name = 22,
    Integer = 23,
    HexInteger = 24,
    Enum = 25,
    Float = 26,
    String = 27,
    LocalString = 28,
    Array = 29,
    Vector = 30,
    Pair = 31,
    KeywordBegin = 32,
    KeywordRepeat = 33,
    KeywordBreak = 34,
    KeywordScript = 35,
    KeywordEndScript = 36,
    KeywordIf = 37,
    KeywordElse = 38,
    KeywordElseIf = 39,
    KeywordEndIf = 40,
    KeywordReturn = 41,
    Undefined = 42,
    ChecksumName = 43,
    KeywordAllArgs = 44,
    Arg = 45,
    Jump = 46,
    KeywordRandom = 47,
    KeywordRandomRange = 48,
    At = 49,
    Or = 50,
    And = 51,
    Xor = 52,
    ShiftLeft = 53,
    ShiftRight = 54,
    KeywordRandom2 = 55,
    KeywordRandomRange2 = 56,
    KeywordNot = 57,
    KeywordAnd = 58,
    KeywordOr = 59,
    KeywordSwitch = 60,
    KeywordEndSwitch = 61,
    KeywordCase = 62,
    KeywordDefault = 63,
    KeywordRandomNoRepeat = 64,
    KeywordRandomPermute = 65,
    Colon = 66,
    RuntimeCFunction = 67,
    RuntimeMemberFunction = 68
}
