using System.IO.Compression;
using System.Text;

namespace NeversoftMultitool.Core.Formats.Archives;

/// <summary>
///     Extracts QTex texture-source bundles: PKZip files named *.tex.zip.wpc / *.tex.zip.ngc
///     shipped in THAW PC/GC under models/**. Each holds the material's original authoring
///     art (TIFF/PNG, including _n/_s normal/specular maps) plus a trailing debug.log of
///     texturetool command lines (EOCD comment "Generated by QTex").
///     The central directory is malformed (garbage extra-field bytes; on some files
///     duplicate CDH records with the CRC-32 written into the compressed-size slot) —
///     strict central-directory readers reject the whole corpus (Python zipfile: 0/1,337).
///     The LOCAL file headers are clean, so this parser walks them sequentially from
///     offset 0 and never touches the central directory.
///     All corpus entries are STORE (method 0); DEFLATE (method 8) is supported so
///     well-formed foreign zips also extract.
/// </summary>
public static class QZipArchive
{
    private const uint LocalHeaderSig = 0x04034B50; // PK\x03\x04
    private const int LocalHeaderSize = 30;
    private const ushort MethodStore = 0;
    private const ushort MethodDeflate = 8;
    private const ushort FlagDataDescriptor = 0x0008;

    /// <summary>
    ///     Returns true if the file starts with a PKZip local file header.
    /// </summary>
    public static bool IsZip(string filePath)
    {
        using var stream = File.OpenRead(filePath);
        if (stream.Length < LocalHeaderSize) return false;
        Span<byte> magic = stackalloc byte[4];
        stream.ReadExactly(magic);
        return BitConverter.ToUInt32(magic) == LocalHeaderSig;
    }

    public static List<ArchiveEntry> GetFileList(string zipPath)
    {
        using var stream = File.OpenRead(zipPath);
        return ReadFileList(stream);
    }

    /// <summary>
    ///     In-memory variant.
    /// </summary>
    public static List<ArchiveEntry> GetFileList(byte[] data)
    {
        using var stream = new MemoryStream(data, false);
        return ReadFileList(stream);
    }

    private static List<ArchiveEntry> ReadFileList(Stream stream)
    {
        using var reader = new BinaryReader(stream, Encoding.UTF8, true);

        var entries = new List<ArchiveEntry>();

        while (stream.Position + LocalHeaderSize <= stream.Length)
        {
            var sig = reader.ReadUInt32();
            if (sig != LocalHeaderSig)
                break; // central directory (or EOCD) reached

            _ = reader.ReadUInt16(); // version needed
            var flags = reader.ReadUInt16();
            var method = reader.ReadUInt16();
            _ = reader.ReadUInt16(); // mod time
            _ = reader.ReadUInt16(); // mod date
            var crc = reader.ReadUInt32();
            var compressedSize = reader.ReadUInt32();
            var uncompressedSize = reader.ReadUInt32();
            var nameLength = reader.ReadUInt16();
            var extraLength = reader.ReadUInt16();

            if ((flags & FlagDataDescriptor) != 0)
                throw new InvalidDataException(
                    "Zip entry uses a data descriptor (sizes unknown at the local header) — unsupported");
            if (method is not MethodStore and not MethodDeflate)
                throw new InvalidDataException($"Unsupported zip compression method {method} (only STORE/DEFLATE)");

            var variableHeaderSize = (long)nameLength + extraLength;
            if (variableHeaderSize > stream.Length - stream.Position)
            {
                throw new InvalidDataException(
                    $"Zip local header declares {nameLength} filename bytes and {extraLength} extra bytes past end of file");
            }

            var nameBytes = reader.ReadBytes(nameLength);
            var name = Encoding.UTF8.GetString(nameBytes).Replace('\\', '/').TrimStart('/');
            stream.Position += extraLength;

            var dataOffset = stream.Position;
            if (dataOffset + compressedSize > stream.Length)
                throw new InvalidDataException($"Zip entry '{name}' data runs past end of file");

            var directory = "";
            var fileName = name;
            var lastSlash = name.LastIndexOf('/');
            if (lastSlash >= 0)
            {
                directory = name[..lastSlash];
                fileName = name[(lastSlash + 1)..];
            }

            // Directory placeholder entries (trailing slash, no data) are not listed.
            if (fileName.Length > 0)
            {
                entries.Add(new ArchiveEntry
                {
                    Name = fileName,
                    Directory = directory,
                    Size = uncompressedSize,
                    Offset = dataOffset,
                    IsCompressed = method == MethodDeflate,
                    CompressedSize = compressedSize,
                    Crc = crc
                });
            }

            stream.Position = dataOffset + compressedSize;
        }

        if (entries.Count == 0)
            throw new InvalidDataException("No zip local file headers found");

        return entries;
    }

    public static void ExtractFiles(string zipPath, string outputDir,
        Action<int, int>? onFileExtracted = null, CancellationToken token = default)
    {
        token.ThrowIfCancellationRequested();
        var entries = GetFileList(zipPath);
        var archiveName = ArchiveNaming.GetExtractionStem(zipPath);
        var outputRoot = Path.GetFullPath(outputDir);
        var extractionRoot = GetContainedExportPath(outputRoot, archiveName);
        var exportPaths = new string[entries.Count];
        for (var i = 0; i < entries.Count; i++)
        {
            token.ThrowIfCancellationRequested();
            exportPaths[i] = GetContainedExportPath(extractionRoot, entries[i].FullName);
        }

        using var stream = File.OpenRead(zipPath);

        for (var i = 0; i < entries.Count; i++)
        {
            token.ThrowIfCancellationRequested();

            var entry = entries[i];
            stream.Seek(entry.Offset, SeekOrigin.Begin);

            var rawData = new byte[entry.CompressedSize];
            stream.ReadExactly(rawData);

            byte[] outputData;
            if (entry.IsCompressed)
            {
                using var deflate = new DeflateStream(new MemoryStream(rawData), CompressionMode.Decompress);
                outputData = new byte[entry.Size];
                deflate.ReadExactly(outputData);
            }
            else
            {
                outputData = rawData;
            }

            var exportPath = exportPaths[i];
            var exportDir = Path.GetDirectoryName(exportPath);
            if (!string.IsNullOrEmpty(exportDir))
                Directory.CreateDirectory(exportDir);

            File.WriteAllBytes(exportPath, outputData);

            onFileExtracted?.Invoke(i + 1, entries.Count);
        }
    }

    internal static string GetContainedExportPath(string extractionRoot, string entryName)
        => ArchiveExtractionPath.GetContainedPath(extractionRoot, entryName, "Zip entry");
}
