namespace NeversoftMultitool.Tests.Core.Formats.Mesh.Detection;

/// <summary>
///     A frozen transcription of the FIVE independent mesh extension lists that
///     existed before <c>MeshTypeDetector</c> folded them together, taken verbatim
///     from HEAD 1e00e24. This is the oracle the parity tests score the detector
///     against: every suffix that routed somewhere before must still route to the
///     same place.
///     <para>
///         The GUI gates are transcribed rather than called because
///         <c>App/**</c> is excluded from the test target framework
///         (NeversoftMultitool.csproj: &lt;Compile Remove="App\**\*.cs" /&gt; for
///         net10.0). Each block below carries the file and line range it came from
///         so a reviewer can diff it against the pre-refactor source.
///     </para>
///     Do not edit this file to make a test pass. If a verdict here is wrong, the
///     legacy code was wrong, and that is a finding to record — not a value to
///     overwrite.
/// </summary>
public static class LegacyMeshRoutingReference
{
    /// <summary>What the legacy code routed a suffix to, independent of content.</summary>
    public enum LegacyKind
    {
        None,
        Collision,
        Ps2Scene,
        Ps2Geom,
        Ps2Worldzone,
        XbxScene,
        Ddm,
        Psx,
        N64Model,
        RenderWareDff,
        RenderWareBsp,
        AmbiguousScene
    }

    // verbatim from Core/FormatProbeMesh.cs:9-13 @ 1e00e24
    public static readonly string[] ProbeXboxSceneSuffixes =
        [".skin.xbx", ".mdl.xbx", ".scn.xbx", ".skin.wpc", ".mdl.wpc", ".scn.wpc", ".skin.ngc", ".mdl.ngc", ".scn.ngc"];

    public static readonly string[] ProbePs2SceneSuffixes = [".skin.ps2", ".mdl.ps2", ".iskin.ps2"];
    public static readonly string[] ProbeCollisionSuffixes = [".col.xbx", ".col.wpc", ".col.ps2", ".col.psp"];

    // verbatim from CLI/MeshCommand.cs:17-22,29 @ 1e00e24
    public static readonly string[] CommandAmbiguousSceneSuffixes = [".skin", ".mdl"];
    public const string CommandN64ModelSuffix = ".psx.n64";

    // verbatim from App/Tabs/MeshConverterTabFileScanner.cs:26-35 @ 1e00e24
    public static readonly string[] ScannerCompoundExtensions =
    [
        ".iskin.ps2", ".skin.ps2", ".mdl.ps2", ".geom.ps2",
        ".skin.xbx", ".mdl.xbx", ".scn.xbx", ".skin.wpc", ".mdl.wpc", ".scn.wpc",
        ".skin.ngc", ".mdl.ngc", ".scn.ngc",
        ".col.xbx", ".col.wpc", ".col.ps2",
        ".pak.ps2"
    ];

    public static readonly string[] ScannerColSuffixes = [".col.xbx", ".col.wpc", ".col.ps2"];

    /// <summary>
    ///     Every suffix that reached a parser before the refactor, with the kind it
    ///     reached. This is the parity surface: the detector must agree on all of
    ///     these. Bare ".col", ".dff" and content-routed bare ".skin" are the three
    ///     deliberate additions and are NOT listed here.
    /// </summary>
    public static IEnumerable<(string Suffix, LegacyKind Kind)> RoutedSuffixes()
    {
        foreach (var suffix in ProbeXboxSceneSuffixes)
            yield return (suffix, LegacyKind.XbxScene);
        foreach (var suffix in ProbePs2SceneSuffixes)
            yield return (suffix, LegacyKind.Ps2Scene);
        foreach (var suffix in ProbeCollisionSuffixes)
            yield return (suffix, LegacyKind.Collision);

        yield return (".geom.ps2", LegacyKind.Ps2Geom);
        yield return (".pak.ps2", LegacyKind.Ps2Worldzone);
        yield return (CommandN64ModelSuffix, LegacyKind.N64Model);
        yield return (".ddm", LegacyKind.Ddm);
        yield return (".psx", LegacyKind.Psx);
        yield return (".skn", LegacyKind.RenderWareDff);
        yield return (".bsp", LegacyKind.RenderWareBsp);

        foreach (var suffix in CommandAmbiguousSceneSuffixes)
            yield return (suffix, LegacyKind.AmbiguousScene);
    }

    // verbatim from CLI/MeshCommand.cs:290-304 @ 1e00e24
    public static bool CommandIsPotentialMeshFile(string name)
    {
        return HasAnySuffix(name, ProbeXboxSceneSuffixes)
               || HasAnySuffix(name, ProbePs2SceneSuffixes)
               || HasAnySuffix(name, ProbeCollisionSuffixes)
               || HasAnySuffix(name, CommandAmbiguousSceneSuffixes)
               || HasSuffix(name, ".geom.ps2")
               || HasSuffix(name, ".pak.ps2")
               || HasSuffix(name, ".ddm")
               || HasSuffix(name, ".psx")
               || HasSuffix(name, CommandN64ModelSuffix)
               || HasSuffix(name, ".skn")
               || HasSuffix(name, ".bsp");
    }

    // verbatim from App/Tabs/MeshConverterTabFileScanner.cs:342-377 @ 1e00e24
    public static bool ScannerIsScanCandidate(string name)
    {
        if (HasSuffix(name, ".iskin.ps2") || HasSuffix(name, ".skin.ps2") || HasSuffix(name, ".mdl.ps2") ||
            HasSuffix(name, ".geom.ps2"))
        {
            return true;
        }

        if (HasSuffix(name, ".skin.xbx") || HasSuffix(name, ".mdl.xbx") ||
            HasSuffix(name, ".scn.xbx") || HasSuffix(name, ".scn.wpc") ||
            HasSuffix(name, ".skin.wpc") || HasSuffix(name, ".mdl.wpc") ||
            HasSuffix(name, ".skin.ngc") || HasSuffix(name, ".mdl.ngc") ||
            HasSuffix(name, ".scn.ngc"))
        {
            return true;
        }

        if (HasAnySuffix(name, ScannerColSuffixes) || HasSuffix(name, ".col"))
            return true;

        if (HasSuffix(name, ".skn") || HasSuffix(name, ".bsp"))
            return true;

        if (HasExtension(name, ".ddm") &&
            !Path.GetFileNameWithoutExtension(name).EndsWith("_o", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (HasSuffix(name, CommandN64ModelSuffix))
            return true;

        return HasExtension(name, ".psx") ||
               HasExtension(name, ".skin") ||
               HasExtension(name, ".mdl");
    }

    // verbatim from CLI/MeshExportCliOptions.cs:193-199 @ 1e00e24
    public static string StripKnownExtension(string file, IEnumerable<string> extensions)
    {
        var fileName = Path.GetFileName(file);
        var matchedExt = extensions.FirstOrDefault(ext =>
            fileName.EndsWith(ext, StringComparison.OrdinalIgnoreCase));
        return matchedExt != null ? fileName[..^matchedExt.Length] : Path.GetFileNameWithoutExtension(fileName);
    }

    // verbatim from CLI/MeshExportCliOptions.cs:201-207 @ 1e00e24
    public static string StripColExtension(string file)
    {
        var stem = Path.GetFileNameWithoutExtension(file);
        if (stem.EndsWith(".col", StringComparison.OrdinalIgnoreCase))
            stem = stem[..^4];
        return stem;
    }

    // verbatim from Core/OrdinalFileName.cs:20-26 @ 1e00e24
    public static string StripCompoundSuffix(string fileName, IReadOnlyList<string> suffixes)
    {
        var suffix = suffixes.FirstOrDefault(candidate => HasSuffix(fileName, candidate));
        return suffix == null
            ? Path.GetFileNameWithoutExtension(fileName)
            : fileName[..^suffix.Length];
    }

    private static bool HasSuffix(string fileName, string suffix)
    {
        return fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasAnySuffix(string fileName, IReadOnlyList<string> suffixes)
    {
        return suffixes.Any(suffix => HasSuffix(fileName, suffix));
    }

    private static bool HasExtension(string path, string extension)
    {
        return Path.GetExtension(path).Equals(extension, StringComparison.OrdinalIgnoreCase);
    }
}
