using System.Collections.Frozen;
using System.Globalization;
using System.Reflection;

namespace NeversoftMultitool.Core.Formats.Texture;

/// <summary>
///   Maps a compiled-texture checksum to the original source-art name, mined from the
///   <c>debug.log</c> that ships inside every THAW QTex <c>.tex.zip</c> bundle
///   (a texturetool build transcript). These checksums are the per-texture keys in the
///   matching <c>.tex.wpc</c>/<c>.tex.ngc</c> headers, so the map lets THAW texture
///   export name its output after the real art (<c>cat_bg_new.png</c>) instead of a hex id.
///   <para>
///   The checksums are opaque build-tool ids, NOT QbKeys — so this is deliberately a
///   SEPARATE resource from <c>QbKeyNames*.txt</c>. It must never be merged into those:
///   they aren't CRC(name) pairs and would poison every proven-name harvest's
///   <c>existing_hashes()</c> and the coverage metrics.
///   Regenerated by <c>tools/utilities/harvest_thaw_texture_names.py</c>.
///   </para>
/// </summary>
public static class ThawTextureNames
{
    private static readonly FrozenDictionary<uint, string> Names = Load();

    /// <summary>Source-art name for a texture checksum, or null if unknown.</summary>
    public static string? TryResolve(uint checksum) =>
        Names.TryGetValue(checksum, out var name) ? name : null;

    private static FrozenDictionary<uint, string> Load()
    {
        var dict = new Dictionary<uint, string>();
        var assembly = typeof(ThawTextureNames).Assembly;
        using var stream = assembly.GetManifestResourceStream("ThawTextureNames.txt");
        if (stream == null)
            return dict.ToFrozenDictionary();

        using var reader = new StreamReader(stream);
        while (reader.ReadLine() is { } line)
        {
            // Format: name=0xHASH
            var eq = line.IndexOf('=');
            if (eq < 1 || eq >= line.Length - 1)
                continue;

            var name = line[..eq];
            if (uint.TryParse(line.AsSpan(eq + 3), NumberStyles.HexNumber, null, out var hash))
                dict.TryAdd(hash, name);
        }

        return dict.ToFrozenDictionary();
    }
}
