using System.Buffers.Binary;
using System.Collections.Frozen;
using System.Globalization;
using NeversoftMultitool.Core.Formats.Mesh.Psx;

namespace NeversoftMultitool.Core.Formats.Mesh.N64;

/// <summary>
///     Real names for carved N64 model bundles, keyed by CONTENT.
///     <para>
///         The Edge of Reality ports re-encoded Neversoft's PS1 <c>.psx</c>
///         containers big-endian and stripped their geometry chunks, but the
///         object table and the QbKey mesh-name hash array survive intact — the
///         <c>models/NNN</c> bundles ARE the PS1 files. Matching a bundle's
///         mesh-name-hash SET against the PS1 corpus therefore names it:
///         measured 2026-08-07 at 433/450 (96.2%) across the four ROMs —
///         THPS1 65/65, THPS2 108/116, THPS3 84/87, Spider-Man 176/182.
///     </para>
///     <para>
///         The PS1 corpus is NOT available at runtime, so identity is harvested
///         offline into an embedded dictionary keyed by a digest the carved
///         shell alone can produce. Same shape as
///         <see cref="Texture.ThawTextureNames" /> and
///         <c>HedDictionary</c> (consumed by <c>WadArchive</c> as
///         <c>TryResolve(hash) ?? hex</c>).
///     </para>
///     <para>
///         These keys are FNV-1a digests of hash SETS, not <c>CRC(name)</c>
///         pairs, so they must never be merged into <c>QbKeyNames*.txt</c> —
///         doing so would poison every proven-name harvest's
///         <c>existing_hashes()</c> and the coverage metric.
///         Regenerated by <c>tools/utilities/harvest_n64_bundle_names.py</c>.
///     </para>
///     <para>
///         AMBIGUITY IS EXPECTED. A hash set describes content, and several PS1
///         files can share content (Spider-Man's <c>l9a3_o</c>/<c>l9a4_o</c>/
///         <c>lba3_o</c>/<c>lba4_o</c> are one 4-mesh set; <c>skss_o</c> and
///         <c>skss_o2</c> are the one- and two-player banks). 95 of 987 keys
///         carry more than one candidate. <see cref="TryResolve" /> returns the
///         first and <see cref="ResolveAll" /> exposes the rest; the carver's
///         slot prefix keeps the emitted path unique either way.
///     </para>
/// </summary>
public static class N64BundleNames
{
    /// <summary>
    ///     Hashes below this are ordinals and sentinels rather than QbKey name
    ///     hashes. The harvest applies the identical filter, so the key is
    ///     computed over the same population the coverage figures were measured
    ///     on — changing it on one side alone silently empties the dictionary.
    /// </summary>
    public const uint MinimumMeshNameHash = 0x1_0000;

    private const ulong FnvBasis = 0xCBF29CE484222325;
    private const ulong FnvPrime = 0x100000001B3;

    private static readonly FrozenDictionary<ulong, string[]> Names = Load();

    private static readonly string[] NoNames = [];

    /// <summary>How many content keys the dictionary carries.</summary>
    public static int Count => Names.Count;

    /// <summary>
    ///     Content digest for a mesh-name hash array: FNV-1a 64 over the
    ///     distinct qualifying hash count as four big-endian bytes, then those
    ///     hashes ascending, four big-endian bytes each.
    ///     <para>
    ///         Order- and duplicate-invariant by construction, so a shell whose
    ///         hashes were read in a different order still keys the same.
    ///         Returns null when nothing qualifies (an empty or stub bundle).
    ///     </para>
    /// </summary>
    public static ulong? ComputeKey(ReadOnlySpan<uint> meshNameHashes)
    {
        var distinct = new SortedSet<uint>();
        foreach (var hash in meshNameHashes)
        {
            if (hash >= MinimumMeshNameHash)
                distinct.Add(hash);
        }

        if (distinct.Count == 0)
            return null;

        Span<byte> word = stackalloc byte[4];
        var digest = FnvBasis;

        BinaryPrimitives.WriteUInt32BigEndian(word, (uint)distinct.Count);
        digest = Absorb(digest, word);
        foreach (var hash in distinct)
        {
            BinaryPrimitives.WriteUInt32BigEndian(word, hash);
            digest = Absorb(digest, word);
        }

        return digest;
    }

    private static ulong Absorb(ulong digest, ReadOnlySpan<byte> bytes)
    {
        foreach (var b in bytes)
            digest = (digest ^ b) * FnvPrime;
        return digest;
    }

    /// <summary>The first candidate name for a content key, or null.</summary>
    public static string? TryResolve(ulong key)
    {
        return Names.TryGetValue(key, out var names) && names.Length > 0 ? names[0] : null;
    }

    /// <summary>
    ///     Every PS1 file whose content matches this key. More than one means
    ///     the files are genuinely indistinguishable by content — each name is
    ///     a true description of what the bundle holds.
    /// </summary>
    public static IReadOnlyList<string> ResolveAll(ulong key)
    {
        return Names.TryGetValue(key, out var names) ? names : NoNames;
    }

    /// <summary>
    ///     Parses a carved big-endian shell and resolves its name in one call.
    ///     Null for stub slots, unparseable buffers and unknown content — the
    ///     carver's only entry point, so a bad shell degrades to a slot name
    ///     rather than throwing during a ROM open.
    /// </summary>
    public static string? TryResolveShell(byte[] shellBytes)
    {
        PsxMeshFile? shell;
        try
        {
            shell = PsxN64ShellFile.Parse(shellBytes);
        }
        catch (Exception ex) when (ex is InvalidDataException or ArgumentException
                                       or IndexOutOfRangeException or ArgumentOutOfRangeException)
        {
            return null;
        }

        if (shell == null || shell.MeshNameHashes.Length == 0)
            return null;

        var key = ComputeKey(shell.MeshNameHashes);
        return key == null ? null : TryResolve(key.Value);
    }

    private static FrozenDictionary<ulong, string[]> Load()
    {
        var dict = new Dictionary<ulong, string[]>();
        var assembly = typeof(N64BundleNames).Assembly;
        using var stream = assembly.GetManifestResourceStream("N64BundleNames.txt");
        if (stream == null)
            return dict.ToFrozenDictionary();

        using var reader = new StreamReader(stream);
        while (reader.ReadLine() is { } line)
        {
            // Format: KEY(16 hex)=stem[|stem...]; '#' comments.
            if (line.Length == 0 || line[0] == '#')
                continue;

            var eq = line.IndexOf('=');
            if (eq < 1 || eq >= line.Length - 1)
                continue;

            if (!ulong.TryParse(line.AsSpan(0, eq), NumberStyles.HexNumber, null, out var key))
                continue;

            dict.TryAdd(key, line[(eq + 1)..].Split('|', StringSplitOptions.RemoveEmptyEntries));
        }

        return dict.ToFrozenDictionary();
    }
}
